apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: hello-pr-
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  resources:
    - name: git-source
      resourceRef:
        name: hello-git
  params:
    - name: pathToYamlFile
      value: "src/tekton/basic/knative/hello.yaml"
    - name: imageUrl
      value: us.icr.io/liuqiang/hello
    - name: imageTag
      value: "1.0"
  serviceAccount: pipeline-account
